# shortcut to this $ZSH path is $ZSH
export ZSH=~/.zsh

# PATH and EXPORT VARIABLES
export SHELL=/usr/local/bin/zsh

export PATH=/usr/local/bin:/usr/local/sbin:./bin:/usr/sbin::~/bin:$ZSH/bin:$PATH
# bundler binstubs i.e. execute rspec without bundle exec
export PATH="./bin:$PATH"

# java home
export JAVA_HOME=$(/usr/libexec/java_home)

# brew cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications" # install cask apps to /Applications

# node path
export NODE_PATH=$(npm root --quiet -g)

# node modules (npm)
export PATH="./node_modules/.bin:$PATH"

# go
export GOPATH=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin

# findutils - gnu from homebrew (findutils)
# export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
# export MANPATH="/usr/local/opt/findutils/libexec/gnuman:$MANPATH"
# coreutils - gnu from homebrew (coreutils)
# export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Get color support for 'less'
export LESS=-RFX
#export LESS="--RAW-CONTROL-CHARS"

# Use colors for less, man, etc.
#[[ -f ~/.LESS_TERMCAP ]] && . ~/.LESS_TERMCAP

# manpath
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"

# manpager
export MANPAGER='less -s -M +Gg' # show percentage progress

export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'
export VIEW="open" # used by google function to open links in browser

# enable colored output from ls, etc
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=1;;40:ln=35;40:so=32;40:pi=33;40:ex=33;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
export CLICOLOR=true

# editor
export EDITOR="vim -v"
#export GIT_EDITOR="vim -v"
export GIT_EDITOR="code --wait"

# rubygems
export GEM_EDITOR="vim -v"

# rbenv configuration
rbenv_exist=$(command -v rbenv >/dev/null 2>&1)
if [[ $rbenv_exist != "" ]]
then
  export PATH="$HOME/.rbenv/bin":$PATH
  eval "$(rbenv init -)"
fi

