# shortcut to this $ZSH path is $ZSH
export ZSH=~/.zsh

# Get color support for 'less'
export LESS=-RFX

# manpager
export MANPAGER='less -s -M +Gg' # show percentage progress

export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'
export VIEW="open" # used by google function to open links in browser

# enable colored output from ls, etc
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=1;;40:ln=35;40:so=32;40:pi=33;40:ex=33;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
export CLICOLOR=true

# editor
export EDITOR="nvim"
export GIT_EDITOR="nvim"
# export GIT_EDITOR="code --wait"

# rubygems
export GEM_EDITOR="vim -v"

# brew cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications" # install cask apps to /Applications

# PATH and EXPORT VARIABLES
export SHELL=/bin/zsh

export PATH=/usr/local/bin:/usr/local/sbin:./bin:/usr/sbin::~/bin:$ZSH/bin:$PATH
export PATH=./bin:${PATH}

# cache for 30 minutes
[ -f $HOME/.cachedenv ] && source $HOME/.cachedenv
. "$HOME/.cargo/env"
