# zmodload zsh/zprof # top of your .zshrc file

# set the keyboard mode in terminal (if loaded after the plugins some stuff dont work)
set -o emacs # or vi if you prefer

# load initial stuff
. $ZSH/config
. $ZSH/prompt
. $ZSH/aliases
. $ZSH/completion
. $ZSH/correction
. $ZSH/key_bindings
. $ZSH/plugins/*

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && . ~/.localrc

# http://talkings.org/post/5236392664/zsh-and-slow-git-completion
# superfly tnt git autocomplete
__git_files () {
  _wanted files expl 'local files' _files
}

# print current directory to title bar
# osx lion now uses that when opening new
# terminal window or tab
# NOTE:
#  - cant figure out the title function yet
#  - also moved precmd and preexec here
#    since i kept forgetting where it was being set
set_title_and_prompt() {
  #title "zsh" "%m" "%55<...<%~"
  #current_directory
  print -Pn "\e]2; ${PWD/#$HOME/~}\a"
  set_prompt
}
precmd () { set_title_and_prompt }
preexec () { set_title_and_prompt }

# get help online from homebrew
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/helpfiles

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'

# fasd
eval "$(fasd --init auto)"

# zsh extra syntax highlighting from brew
[ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# nodenv
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

# npmbrew
export PATH=$HOME/.npmbrew/current/bin:$PATH

# python - use pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# must be last thing otherwise it locks up the terminal. Should just probably move to rbenv
export PATH="/usr/local/bin:$PATH"
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=/Users/kaks/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# zprof
