# zmodload zsh/zprof # top of your .zshrc file

# set the keyboard mode in terminal (if loaded after the plugins some stuff dont work)
set -o emacs # or vi if you prefer

# load initial stuff
. $ZSH/config
. $ZSH/prompt
. $ZSH/aliases
. $ZSH/completion
. $ZSH/correction
. $ZSH/key_bindings
for file in $ZSH/plugins/**/*(.); do source $file; done
for file in $HOME/.tmux/zsh/**/*.plugin.zsh(.N); do source $file; done


# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && . ~/.localrc

# http://talkings.org/post/5236392664/zsh-and-slow-git-completion
# superfly tnt git autocomplete
# __git_files () {
#   _wanted files expl 'local files' _files
# }

# print current directory to title bar
set_title_and_prompt() {
  # print -Pn "\e]2; ${PWD/#$HOME/~}\a"
  set_prompt
}
precmd () { set_title_and_prompt }
preexec () { set_title_and_prompt }

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'

# fasd
# eval "$(fasd --init auto)"

# zsh extra syntax highlighting from brew
[ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=~/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# using python instead of /usr/bin/stat directly
# https://github.com/aluxian/fish-kube-prompt/pull/11/files
__stat_mtime () {
  #-- cross-platform workaround; POSIX didn't specify stat(1) and so
  #-- its interface is incompatibly different on Mac OS and Linux.
  #-- see https://unix.stackexchange.com/q/561927/3097
  python -c "print(__import__('os').stat(__import__('sys').argv[1]).st_mtime)" $argv
}

lastmod () {
	local result=$(( $(date +"%s") - $(__stat_mtime "%m" $1) ))
  return result
}

stale () {
  local filename=$1
  local maxminutes=$2
  [[ $(lastmod $filename; echo $?) -gt $maxminutes*60 ]]
}

cacheplease () {
  if [ -f $1 ] && ! stale $1 $2; then
    #echo "exists"
    source $1
  else
    #echo "reload"
    local before=$(ENV)

    # manpath
    export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"

    # node modules (npm)
    export PATH="./node_modules/.bin:$PATH"

    # java home
    export JAVA_HOME=$(/usr/libexec/java_home)

    # node path
    # export NODE_PATH=$(npm root --quiet -g)

    # go
    export GOROOT=$(brew --prefix golang)/libexec
    export GOPATH=$HOME/go
    export PATH=$GOPATH/bin:${GOROOT}/bin:$PATH

    # nodenv -- use "--no-rehash" for faster initialization
    # if which nodenv 1>/dev/null 2>&1; then eval "$(nodenv init - zsh)"; fi

    # pyenv 
    if which pyenv 1>/dev/null 2>&1; then 
	    export PYENV_ROOT="$HOME/.pyenv"
	    export PATH="$PYENV_ROOT/bin:$PATH"
	    eval "$(pyenv init --path)"
	    eval "$(pyenv init - zsh)"; 
    fi

    # elastic beanstalk
    export PATH="$HOME/.ebcli-virtual-env/executables:$PATH"


    local after=$(ENV)

    output=$(comm -23 <(printf '%s\n' $after) <(printf '%s\n' $before))
    echo $output | sed 's/^\(.*\)=\(.*\)$/\1="\2"/' > $1
  fi
}
# cache for X minutes
#cacheplease $HOME/.cachedenv 18000

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH=/opt/local/bin:/opt/local/sbin:$PATH


# pnpm
export PNPM_HOME=$HOME/Library/pnpm
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kaks/SynologyDrive/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/kaks/SynologyDrive/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kaks/SynologyDrive/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/kaks/SynologyDrive/Downloads/google-cloud-sdk/completion.zsh.inc'; fi


vv() {
  select config in lazy own
  do NVIM_APPNAME=nvim-$config nvim $@; break; done
}

# gwt (git worktree helper, ~/.dotfiles/bin/gwt): a script can't cd its parent
# shell, so for the create/switch verbs we cd into the path it prints on stdout.
# from/co with no args open an fzf picker inside the script and signal back with
# a GWT_POPULATE: prefix; the wrapper writes that into the line buffer via
# print -z so you can review/add flags before hitting Enter.
gwt() {
  case "$1" in
    new|from|co|checkout|search|pick)
      local out; out=$(command gwt "$@") || return
      if [[ $out == GWT_POPULATE:* ]]; then
        print -z "${out#GWT_POPULATE:}"
      else
        builtin cd "${out##*$'\n'}" && command gwt ls
      fi ;;
    *) command gwt "$@" ;;
  esac
}

# adding shitty NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

function change_node_version {
	nvmrc="./.nvmrc"
	if [ -f "$nvmrc" ]; then
		version="$(cat "$nvmrc")"
		nvm use $version
	fi
}
chpwd_functions=(change_node_version)


test -e "${HOME}/.zshrc.local" && source "${HOME}/.zshrc.local"


[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/kyriacos/.cache/lm-studio/bin"
export PATH="$HOME/.local/bin:$PATH"

# bun completions
[ -s "/Users/kyriacos/.bun/_bun" ] && source "/Users/kyriacos/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Added by Antigravity
export PATH="/Users/kyriacos/.antigravity/antigravity/bin:$PATH"
